[[bacnet_stack]]
arch = "aarch64"
git-tree-sha1 = "90b13bed72c56bd5253a76f9dfec598f27b838f8"
os = "macos"

    [[bacnet_stack.download]]
    sha256 = "7abc0d1b6aaa0389370889bd434dcf38c05c4d2b5aa1cf617e59d2fc908d9fb0"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.aarch64-apple-darwin.tar.gz"
[[bacnet_stack]]
arch = "aarch64"
git-tree-sha1 = "d7c570ffaa3aa33a727e9328d7511c8988bab665"
libc = "glibc"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "fcd55995dfea7586c99fa4fa804fd820d6187353565fad8ec4e198363411bd9a"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.aarch64-linux-gnu.tar.gz"
[[bacnet_stack]]
arch = "aarch64"
git-tree-sha1 = "cb98b27a9f41033d3944af754963822c376aa1de"
libc = "musl"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "6790c5a2eb8fe650d0aff0c5d3fd7c691224eaea8db14fb5130d45dae0360e67"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.aarch64-linux-musl.tar.gz"
[[bacnet_stack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f5be90a30fe3737c7dfcb7be5f0f2840ff1e0c7"
libc = "glibc"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "db60996ae6a3b50de982288a3180ee1aab5a1e0460d8133de475a1a1196381da"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.armv6l-linux-gnueabihf.tar.gz"
[[bacnet_stack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "928f8ea185106453c38055bfe6f260e4a0d042df"
libc = "musl"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "8d3c96ca05c21be9efa51c1eabfeea6b8a8fc99d8b6de711b89c7e091a4025f2"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.armv6l-linux-musleabihf.tar.gz"
[[bacnet_stack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51c6713edf5b2c9c60bfa0d8a4b15488bb2371cd"
libc = "glibc"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "13df0e58b2f455fb5e1d043e55a5b722580e0fde192a348aedc885c697e13f51"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.armv7l-linux-gnueabihf.tar.gz"
[[bacnet_stack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b298e79cf84a13214e4b3866832add031c602c5f"
libc = "musl"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "74d54666d8be6cbc1564cac54516d42a8d7706ce0160ede8abddd7e6c171fbb5"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.armv7l-linux-musleabihf.tar.gz"
[[bacnet_stack]]
arch = "i686"
git-tree-sha1 = "f6fa20813780a77384d57cad99c2ac9280e262bb"
libc = "glibc"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "7d654454b281f0d8c3442c345879081f628ca9af5e9db0a7362fc2cae59c043b"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.i686-linux-gnu.tar.gz"
[[bacnet_stack]]
arch = "i686"
git-tree-sha1 = "030fc507c10fd2d0ed5a9597024d9ebdd2a350e8"
libc = "musl"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "53696ac4d5607b4011bb4e7de3424f29a1153fcf1c01e00894cb0a5c09d5857d"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.i686-linux-musl.tar.gz"
[[bacnet_stack]]
arch = "i686"
git-tree-sha1 = "484f7e6027567a486d411d0dade1c368f745e40c"
os = "windows"

    [[bacnet_stack.download]]
    sha256 = "a0a659b50a91f8e8dd3bbb5869196b4c71c1d8e313750014f732dfb0d6ad6322"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.i686-w64-mingw32.tar.gz"
[[bacnet_stack]]
arch = "powerpc64le"
git-tree-sha1 = "16937f8c7c145a6ed33ff52206e140e827a81299"
libc = "glibc"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "5dd45f3c74bc24a2bf4fe78f96e1a640797834d1b8d9f2dcd42dd10ca4d32634"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.powerpc64le-linux-gnu.tar.gz"
[[bacnet_stack]]
arch = "riscv64"
git-tree-sha1 = "1cbe0ebc9e5936742089d277f54f9bdde2496abd"
libc = "glibc"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "3b3ca2b6e57c188cfb4de4d0e9ead786156f77fb334d099470d81e18995ea5c3"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.riscv64-linux-gnu.tar.gz"
[[bacnet_stack]]
arch = "x86_64"
git-tree-sha1 = "5231bf0f747ec38a37c1e82ccc1579ac0bc49e3e"
os = "macos"

    [[bacnet_stack.download]]
    sha256 = "db1ddaf0406895cdb7f360a187574e8fb2f240c478b165324e6ef4492e76ce7a"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.x86_64-apple-darwin.tar.gz"
[[bacnet_stack]]
arch = "x86_64"
git-tree-sha1 = "fd4b452f5ca0f762b4032812331fe43af843e9db"
libc = "glibc"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "ea73c700c4a09b009a09822d8db7a93aad2ff73f76afdd2ed532785182caa4aa"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.x86_64-linux-gnu.tar.gz"
[[bacnet_stack]]
arch = "x86_64"
git-tree-sha1 = "9811f8e00a60b79dc96061d59426b07853b85e4d"
libc = "musl"
os = "linux"

    [[bacnet_stack.download]]
    sha256 = "80893d4b5c55c9b059a772c10540d895012f003babca99cc3319b509df124bd0"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.x86_64-linux-musl.tar.gz"
[[bacnet_stack]]
arch = "x86_64"
git-tree-sha1 = "a2b5850d1bd19e17293b246a6bf0e8bd6b701b31"
os = "windows"

    [[bacnet_stack.download]]
    sha256 = "11ab1c83500d71e5e80776ac261f391324dd5781b1a3c5a39649dfe08cb687f1"
    url = "https://github.com/JuliaBinaryWrappers/bacnet_stack_jll.jl/releases/download/bacnet_stack-v1.4.1+1/bacnet_stack.v1.4.1.x86_64-w64-mingw32.tar.gz"
