# Autogenerated wrapper script for bacnet_stack_jll for armv7l-linux-musleabihf
export libbacnet_stack

JLLWrappers.@generate_wrapper_header("bacnet_stack")
JLLWrappers.@declare_library_product(libbacnet_stack, "libbacnet-stack.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbacnet_stack,
        "lib/libbacnet-stack.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
