# Autogenerated wrapper script for bacnet_stack_jll for x86_64-apple-darwin
export libbacnet_stack

JLLWrappers.@generate_wrapper_header("bacnet_stack")
JLLWrappers.@declare_library_product(libbacnet_stack, "@rpath/libbacnet-stack.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbacnet_stack,
        "lib/libbacnet-stack.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
